/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "inverse-surface": "#dce1fb",
        "on-error-container": "#ffdad6",
        "primary-fixed-dim": "#adc6ff",
        "on-secondary": "#283044",
        "error-container": "#93000a",
        "on-surface-variant": "#c2c6d6",
        "on-tertiary-fixed-variant": "#38485d",
        "on-secondary-fixed": "#131b2e",
        "on-primary-container": "#00285d",
        "on-primary-fixed": "#001a42",
        "inverse-on-surface": "#2a3043",
        "tertiary-fixed-dim": "#b7c8e1",
        "tertiary-fixed": "#d3e4fe",
        "on-background": "#dce1fb",
        "secondary-container": "#3f465c",
        "on-primary-fixed-variant": "#004395",
        "error": "#ffb4ab",
        "surface-container-low": "#151b2d",
        "on-secondary-container": "#adb4ce",
        "on-secondary-fixed-variant": "#3f465c",
        "on-surface": "#dce1fb",
        "background": "#0c1324",
        "primary": "#adc6ff",
        "surface-container-high": "#23293c",
        "secondary": "#bec6e0",
        "surface-container": "#191f31",
        "primary-container": "#4d8eff",
        "outline-variant": "#424754",
        "outline": "#8c909f",
        "secondary-fixed-dim": "#bec6e0",
        "surface-variant": "#2e3447",
        "on-error": "#690005",
        "on-tertiary": "#213145",
        "secondary-fixed": "#dae2fd",
        "inverse-primary": "#005ac2",
        "surface-container-highest": "#2e3447",
        "surface-container-lowest": "#070d1f",
        "on-tertiary-container": "#1a2b3e",
        "on-primary": "#002e6a",
        "surface": "#0c1324",
        "tertiary-container": "#8292aa",
        "primary-fixed": "#d8e2ff",
        "surface-tint": "#adc6ff",
        "on-tertiary-fixed": "#0b1c30",
        "surface-bright": "#33394c",
        "surface-dim": "#0c1324",
        "tertiary": "#b7c8e1"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "md": "1rem",
        "xl": "2rem",
        "margin-desktop": "2.5rem",
        "max-width": "1440px",
        "margin-mobile": "1rem",
        "xs": "0.25rem",
        "sm": "0.5rem",
        "gutter": "1.5rem",
        "lg": "1.5rem"
      },
      "fontFamily": {
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"]
      },
      "fontSize": {
        "headline-lg-mobile": ["28px", {"lineHeight": "36px", "fontWeight": "700"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-sm": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "headline-xl": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
