# Generated by Django 5.2.14 on 2026-05-10 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('e_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mob_no', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pin_no', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'employee',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('age', models.PositiveIntegerField()),
                ('dob', models.DateField()),
                ('mob_no', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'patient',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('record_no', models.AutoField(primary_key=True, serialize=False)),
                ('app_no', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'records',
                'ordering': ['record_no'],
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('General', 'General'), ('Private', 'Private'), ('ICU', 'ICU'), ('Emergency', 'Emergency'), ('Operation Theatre', 'Operation Theatre'), ('Maternity', 'Maternity')], max_length=50)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('availability', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'rooms',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=200)),
                ('e_id', models.OneToOneField(db_column='e_id', on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to='hospital.employee')),
            ],
            options={
                'db_table': 'doctor',
                'ordering': ['dept'],
            },
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('nurse_id', models.AutoField(primary_key=True, serialize=False)),
                ('e_id', models.OneToOneField(db_column='e_id', on_delete=django.db.models.deletion.CASCADE, related_name='nurse_profile', to='hospital.employee')),
            ],
            options={
                'db_table': 'nurse',
            },
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('b_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='hospital.patient')),
            ],
            options={
                'db_table': 'bills',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('receptionist_id', models.AutoField(primary_key=True, serialize=False)),
                ('e_id', models.OneToOneField(db_column='e_id', on_delete=django.db.models.deletion.CASCADE, related_name='receptionist_profile', to='hospital.employee')),
            ],
            options={
                'db_table': 'receptionist',
            },
        ),
        migrations.CreateModel(
            name='Assigned',
            fields=[
                ('assign_id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_assignments', to='hospital.patient')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_assignments', to='hospital.rooms')),
            ],
            options={
                'db_table': 'assigned',
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.CreateModel(
            name='Test_Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_type', models.CharField(max_length=150)),
                ('result', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_reports', to='hospital.patient')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_reports', to='hospital.rooms')),
            ],
            options={
                'db_table': 'test_report',
                'ordering': ['-report_id'],
            },
        ),
        migrations.CreateModel(
            name='Consults',
            fields=[
                ('consult_id', models.AutoField(primary_key=True, serialize=False)),
                ('consult_date', models.DateField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='hospital.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='hospital.patient')),
            ],
            options={
                'db_table': 'consults',
                'ordering': ['-consult_date'],
                'unique_together': {('patient', 'doctor', 'consult_date')},
            },
        ),
        migrations.CreateModel(
            name='Maintains',
            fields=[
                ('maintain_id', models.AutoField(primary_key=True, serialize=False)),
                ('receptionist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintained_records', to='hospital.receptionist')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintained_by', to='hospital.records')),
            ],
            options={
                'db_table': 'maintains',
                'unique_together': {('receptionist', 'record')},
            },
        ),
        migrations.CreateModel(
            name='Governs',
            fields=[
                ('govern_id', models.AutoField(primary_key=True, serialize=False)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='governed_rooms', to='hospital.nurse')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='governing_nurses', to='hospital.rooms')),
            ],
            options={
                'db_table': 'governs',
                'unique_together': {('nurse', 'room')},
            },
        ),
    ]
