# Generated by Django 5.2.14 on 2026-05-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_patient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
